import "./indicators/sma";
import "./indicators/bollinger";
import "./indicators/gaps";
import "./indicators/ema";
import "./indicators/direction";
import "./indicators/extrema";
import "./indicators/trends";
import "./indicators/bollinger-percent-b";
import "./indicators/bollinger-bandwidth";
import "./indicators/days-falling";
import "./indicators/days-rising";
import "./indicators/momentum";
import "./indicators/rate-of-change";
import "./indicators/rsi";
import "./indicators/streaks";
import "./indicators/conners-rsi";
import "./indicators/macd";
import "./indicators/stochastic-fast"
import "./indicators/stochastic-slow"